image: Visual Studio 2022

environment:
  STACKEXCHANGE_REDIS_TESTS_AZURE_SERVERNAME:
    secure: r3KZkWNHP0m7gN1MerZ8WAnwAnL/wsWUmmgWwPpFph6rw5t+k/Xn96iP7CCu3XLt
  STACKEXCHANGE_REDIS_TESTS_AZURE_PASSWORD:
    secure: WwryINia1gbEsKxBQ3ont5ENcyVZctp6MS3OA/tUHtQg6mOjZ8aeK853UGaCQEuc

install:
- cmd: >-
    cd RedisConfigs\3.0.503

    call install-services.cmd

    cd ..\..
- ps: Start-Service redis-*

build_script:
- ps: .\build.ps1 -BuildNumber "$env:APPVEYOR_BUILD_NUMBER" -Version "$env:APPVEYOR_REPO_TAG_NAME" -PullRequestNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -CreatePackages $true -RunTests $true

test: off

artifacts:
- path: .\.nupkgs\*.nupkg